name: IPTV Otomatik Guncelleme

on:
  schedule:
    - cron: '0 */6 * * *' # Her 6 saatte bir otomatik çalışır
  workflow_dispatch: # Manuel tetikleme butonu ekler

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Kütüphaneleri Yükle
      run: pip install requests beautifulsoup4

    - name: Scripti Çalıştır
      run: python iptv_generator.py

    - name: Değişiklikleri Kaydet ve GitHub'a Yükle
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add arabbul.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Güncel IPTV Kanalları" && git push)
